# Generated by Django 5.0.3 on 2024-03-10 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homepage_works_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='profile_pic',
        ),
    ]
