# Generated by Django 5.0.3 on 2024-03-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_homepage_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
