# Generated by Django 5.0.3 on 2024-03-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_about_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='core/media/core'),
        ),
    ]
