# Generated by Django 5.0.3 on 2024-03-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_about_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profile_picture',
            field=models.ImageField(default='core/default.png', upload_to=''),
        ),
    ]
