# Generated by Django 5.0.3 on 2024-03-19 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_about_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='about',
            name='welcome',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='time_stamp',
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
