# Generated by Django 5.0.3 on 2024-03-20 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_about_introduction_remove_about_welcome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='time_stamp',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
