# Generated by Django 5.0.3 on 2024-03-24 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_education_time_stamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
